import tkinter as tk
from tkinter import filedialog, messagebox
import os
import hashlib
import datetime


window = tk.Tk()

window.title("Digital Forensics Evidence Analyzer")
window.geometry("650x700")


evidence = {}


def choose_file():
    file_path = filedialog.askopenfilename()

    if file_path:
        file_name = os.path.basename(file_path)
        file_size = os.path.getsize(file_path)

        # Calculate SHA-256
        with open(file_path, "rb") as file:
            file_hash = hashlib.sha256(file.read()).hexdigest()

        # Get file type
        file_type = os.path.splitext(file_name)[1]

        # Get timestamps
        created_time = os.path.getctime(file_path)
        modified_time = os.path.getmtime(file_path)

        created = datetime.datetime.fromtimestamp(created_time)
        modified = datetime.datetime.fromtimestamp(modified_time)

        # Store evidence information
        evidence["file_name"] = file_name
        evidence["file_size"] = file_size
        evidence["file_type"] = file_type
        evidence["created"] = created
        evidence["modified"] = modified
        evidence["sha256"] = file_hash

        # Display information
        name_label.config(text="File Name: " + file_name)
        size_label.config(text="File Size: " + str(file_size) + " bytes")
        type_label.config(text="File Type: " + file_type)
        created_label.config(text="Created: " + str(created))
        modified_label.config(text="Modified: " + str(modified))
        hash_label.config(text="SHA-256: " + file_hash)


def create_report():
    if not evidence:
        messagebox.showwarning(
            "No Evidence",
            "Please choose an evidence file first."
        )
        return ""

    report = f"""
DIGITAL FORENSICS EVIDENCE REPORT
=================================

File Name: {evidence["file_name"]}
File Size: {evidence["file_size"]} bytes
File Type: {evidence["file_type"]}

Created: {evidence["created"]}
Modified: {evidence["modified"]}

SHA-256:
{evidence["sha256"]}

HASH IMPORTANCE
---------------
A cryptographic hash acts as a digital fingerprint of a file.

If the contents of the file change, its hash value will normally
change as well.

This can help investigators verify the integrity of evidence
during forensic analysis.

=================================
Report generated by Digital Forensics Evidence Analyzer
"""

    return report


def generate_report():
    report = create_report()

    if report:
        with open("evidence_report.txt", "w") as report_file:
            report_file.write(report)

        messagebox.showinfo(
            "Report Generated",
            "Evidence report created successfully!"
        )


def export_report():
    report = create_report()

    if not report:
        return

    save_location = filedialog.asksaveasfilename(
        defaultextension=".txt",
        filetypes=[
            ("Text Files", "*.txt"),
            ("All Files", "*.*")
        ],
        title="Export Evidence Report"
    )

    if save_location:
        with open(save_location, "w") as report_file:
            report_file.write(report)

        messagebox.showinfo(
            "Export Successful",
            "Evidence report exported successfully!"
        )


title = tk.Label(
    window,
    text="🔎 Digital Forensics Evidence Analyzer",
    font=("Arial", 20)
)

title.pack(pady=25)


choose_button = tk.Button(
    window,
    text="📁 Choose Evidence File",
    command=choose_file,
    font=("Arial", 14)
)

choose_button.pack(pady=10)


name_label = tk.Label(
    window,
    text="File Name: Not selected",
    font=("Arial", 11)
)

name_label.pack(pady=5)


size_label = tk.Label(
    window,
    text="File Size: Not selected",
    font=("Arial", 11)
)

size_label.pack(pady=5)


type_label = tk.Label(
    window,
    text="File Type: Not selected",
    font=("Arial", 11)
)

type_label.pack(pady=5)


created_label = tk.Label(
    window,
    text="Created: Not available",
    font=("Arial", 11)
)

created_label.pack(pady=5)


modified_label = tk.Label(
    window,
    text="Modified: Not available",
    font=("Arial", 11)
)

modified_label.pack(pady=5)


hash_label = tk.Label(
    window,
    text="SHA-256: Not calculated",
    font=("Arial", 9),
    wraplength=600
)

hash_label.pack(pady=10)


report_button = tk.Button(
    window,
    text="📄 Generate Evidence Report",
    command=generate_report,
    font=("Arial", 13)
)

report_button.pack(pady=10)


export_button = tk.Button(
    window,
    text="💾 Export Report",
    command=export_report,
    font=("Arial", 13)
)

export_button.pack(pady=10)


window.mainloop()